#!/usr/bin/env sh

#
# for this to work you must configure sudo such that
# it will be able to run the command without password
#
# see this wiki page for information:
#  - https://github.com/koekeishiya/yabai/wiki/Installing-yabai-(latest-release)#configure-scripting-addition
#
# yabai -m signal --add event=dock_did_restart action="sudo yabai --load-sa"
# sudo yabai --load-sa
#

# global settings
yabai -m config \
	external_bar off:40:0 \
	menubar_opacity 1.0 \
	mouse_follows_focus off \
	focus_follows_mouse off \
	window_origin_display default \
	window_placement second_child \
	window_zoom_persist on \
	window_shadow on \
	window_animation_duration 0.0 \
	window_opacity_duration 0.0 \
	active_window_opacity 1.0 \
	normal_window_opacity 0.90 \
	window_opacity off \
	insert_feedback_color 0xffd75f5f \
	split_ratio 0.50 \
	split_type auto \
	auto_balance off \
	top_padding 10 \
	bottom_padding 10 \
	left_padding 10 \
	right_padding 10 \
	window_gap 05 \
	layout bsp \
	mouse_modifier alt \
	mouse_action1 move \
	mouse_action2 resize \
	mouse_drop_action swap

yabai -m rule --add app="^(System Settings|系统设置)" manage=off

yabai -m rule --add app="^(微信|Wechat)" manage=off

yabai -m rule --add app="^(QQ|TIM)" manage=off

yabai -m rule --add app="^(访达|Finder)" manage=off

yabai -m rule --add app="^(NeatDownloadManager)" manage=off

yabai -m rule --add app="^(信息)" manage=off

yabai -m rule --add app="^(WhatsApp)" manage=off

yabai -m rule --add app="^(音乐)" title="迷你播放程序" manage=off

yabai -m rule --add app="^(FaceTime通话)" manage=off

yabai -m rule --add app="^(masterduel.exe)" manage=off

borders active_color=0xffe1e3e4 inactive_color=0xff494d64 width=5.0 hidpi=on style=round ax_focus=on &

echo "yabai configuration loaded.."
